import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  wrapper: {},
  slide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  image: {
    width: '100%',
    height: '50%',
    marginTop:-375
  },
  textContainer: {
    padding: 20,
  },
  button: {
    backgroundColor: '#2BC957',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  title: {
    marginTop:-350,
    fontSize: 50,
    fontFamily:'Montserrat-MediumItalic',
    color: 'white',
    marginBottom: 10,
  },
  subtitle: {
    margin:30,
    fontSize: 16,
    color: 'white',
    marginBottom: 10,
  },
  description: {
    margin:30,
    marginTop:200,
    fontSize: 24,
    color: 'black',
  },
  nextButton: {
    marginTop: 300,
    alignSelf: 'flex-end',
  },
  nextButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  icon: {
    marginTop:30,
    margin:15,
    width:133,
    height:50,
    backgroundColor:'#2BC957',
    borderRadius:7,
    justifyContent:'center',
    alignItems:'center',
  },
  iconText: {
    marginTop:-2,
    fontSize:22,
    color:'#fff',
    fontWeight:'400',
  },
  icon1: {
    marginLeft:-190,
    marginTop:-290,
    margin:15,
    width:133,
    height:50,
    backgroundColor:'#2BC957',
    borderRadius:7,
    justifyContent:'center',
    alignItems:'center',
  },
  iconText2: {
    marginTop:-2,
    fontSize:22,
    color:'#fff',
    fontWeight:'400',
  },
  dot: {
    backgroundColor: 'gray',
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  activeDot: {
    backgroundColor: '#00cc00',
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  image1: {
    width: '100%',
    height: '50%',
    marginTop:-80,
  },
  description1: {
    fontSize: 14,
    color: 'white',
    marginBottom: 10,
    textAlign: 'center',
  },
  slide1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2BC957',
  },
  triangle: {
    marginTop:-367,
      width: 0,
      height: 0,
      borderRightWidth: 412,
      borderBottomWidth: 100,
      borderRightColor: 'transparent',
      borderBottomColor: '#2BC957',
  },
  icon2: {
    marginLeft:-190,
    marginTop:-50,
    margin:15,
    width:133,
    height:50,
    backgroundColor:'#fff',
    borderRadius:7,
    justifyContent:'center',
    alignItems:'center',
  },
  iconText3: {
    marginTop:-2,
    fontSize:22,
    color:'#000',
    fontWeight:'400',
  },
});
export default styles
